# A descriptive name for your workflow
name: Deploy Website to GitHub Pages

# Controls when the workflow will run
on:
  # Runs on pushes targeting the `main` branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions the workflow needs to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" job is responsible for creating your website files
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Step 1: Get a copy of your code

      #      - name: Set up Python
      #        uses: actions/setup-python@v5 # Step 2: Install Python
      #        with:
      #          python-version: '3.11'
      #
      #      - name: Install Pygame dependencies
      #        run: pip install pygbag # Step 3: Install pygbag
      #
      #      - name: Build Pygame games for the web
      #        run: |
      #          Add a build command here for EACH of your games
      #          pygbag games/minesweeper/
      #          pygbag games/another-game/
      - name: Assemble final website in /dist folder
        run: |
          #          mkdir dist # Create the distribution directory
          # Copy the main website files
          cp src/index.html src/data.json dist/
          cp games/minesweeper/index.html dist/minesweeper
          # Copy the compiled game folders
          # Add a copy command here for EACH of your games
          #          cp -r games/minesweeper/build/web dist/minesweeper
          # cp -r games/another-game/build/web dist/another-game

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Step 4: Upload the /dist folder
        with:
          path: ./dist

  # The "deploy" job takes the built site and deploys it
  deploy:
    needs: build # This job will only run after the "build" job is successful
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Step 5: Deploy the artifact to Pages